name: Deployment
on:
  push:
    branches:
      - main

env:
    REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ShareBoxAPI
        push: true
        tags: '${{ env.REGISTRY }}/${{ secrets.USERNAME }}/shareboxapi:latest'
